# Module manifest for module 'NewShellServer'
# Generated by: henri
# Generated on: 25/09/2026

@{
RootModule = 'NewShellServer.dll'
ModuleVersion = '0.0.3'
GUID = 'fc7d4da6-6fb2-44ce-8c5f-1505a51389d2'
Author = 'Henrique do Val'
Copyright = '(c) Henrique do Val. All rights reserved.'
Description = 'PowerShell client module for New ShellServer'

# PowerShellVersion = '7.2'  # Not sure

ScriptsToProcess = @("SetPromptText.ps1")

CmdletsToExport = @(
        'Set-ShellServerLocation',
        'Edit-ShellServerCache',
        'Show-ShellServerCache',
        'Save-ShellServerCache',
        'Invoke-ShellServerPrompt',
        'Update-ShellServerConfig'
    )

AliasesToExport = @('p', 'pe', 'prompt')
VariablesToExport = '*'
FunctionsToExport = @()

PrivateData = @{
    PSData = @{
        Tags = @("prompt", "navigation")
        LicenseUri = 'https://github.com/HenriquedoVal/new-shellserver-clients/LICENSE'
        ProjectUri = 'https://github.com/HenriquedoVal/new-shellserver-clients'
    }
}
}
